name: test
on:   
  push:
    branches: [ master ]
    paths-ignore:
     - '**.md'
     #- '**.yml'
     - '**.yaml' 
  pull_request:
    branches: [ master ]
    paths-ignore:
     - '**.md'
     #- '**.yml'
     - '**.yaml'     
env:
  GOPROXY: "https://proxy.golang.org"
  GO_VERSION: 1.16
jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{env.GO_VERSION}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v2
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download
      - name: Build example
        run: go build -o example-bin ./example/example.go
      - name: Test
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0